spring:
  jms:
    servicebus:
      connection-string: Endpoint=https://asb_host:5671/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xx
      idle-timeout: 1800000

queue:
  boot: q.GAP
  incoming:
    name: in-queue.q

camel:
  queue:
    incoming:
      name: amqp:queue:in-queue.q
    outcoming:
      name: amqp:queue:out-queue.q
